<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>ConsoleEngine.SceneRunner</AssemblyName>
    <RootNamespace>ConsoleEngine.SceneRunner</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ConsoleEngine.Scenes\ConsoleEngine.Scenes.csproj" />
  </ItemGroup>

</Project>
